engines:
  pep8:
    enabled: true
  radon: 
    enabled: true
    config: 
      python_version: 3
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
          mass_threshold: 32
  fixme:
    enabled: true

ratings:
  paths:
    - "**.py"
exclude_paths:
  - "docs/"
  - "examples/"
  - "benchmarks/"
